const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Orbit,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Behaviors.Anchor,
		C3.Behaviors.Rotate,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Pin,
		C3.Plugins.NinePatch,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Plugins.Cryptography,
		C3.Plugins.BinaryData,
		C3.Plugins.filechooser,
		C3.Plugins.Json,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.min,
		C3.Behaviors.Orbit.Exps.Rotation,
		C3.Behaviors.Orbit.Acts.SetRadius,
		C3.Plugins.Sprite.Exps.IID,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Orbit.Acts.SetRotation,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.System.Exps.tokenat,
		C3.Behaviors.Pin.Acts.PinByDistance,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.SetLayerScroll,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.NinePatch.Acts.SetX,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.SetPos,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.TiledBg.Cnds.CompareHeight,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Exps.Magnitude,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Json.Acts.SetInstanceVar,
		C3.Plugins.Json.Acts.SetObject,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Json.Acts.AddInstanceVar,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Json.Cnds.CompareInstanceVar,
		C3.Plugins.BinaryData.Acts.SetFromText,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.Cryptography.Acts.EncryptBinary,
		C3.Plugins.Cryptography.Cnds.OnEncryptionFinished,
		C3.Plugins.Browser.Acts.InvokeDownloadString,
		C3.Plugins.BinaryData.Exps.GetBase64,
		C3.Plugins.filechooser.Acts.Click,
		C3.Plugins.filechooser.Cnds.OnChanged,
		C3.Plugins.filechooser.Exps.FileCount,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.filechooser.Exps.FileURLAt,
		C3.Plugins.BinaryData.Acts.SetFromBase64,
		C3.Plugins.Cryptography.Acts.DecryptBinary,
		C3.Plugins.Cryptography.Cnds.OnDecryptionFinished,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.BinaryData.Exps.GetAllText,
		C3.JavaScriptInEvents.Menu_sheet_Event4_Act1,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.TiledBg.Exps.IID,
		C3.Plugins.TiledBg.Exps.ColorValue,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.Menu_sheet_Event30_Act1,
		C3.JavaScriptInEvents.Menu_sheet_Event31_Act1,
		C3.Plugins.System.Exps.layoutname,
		C3.JavaScriptInEvents.Ads_Event1_Act1,
		C3.JavaScriptInEvents.Ads_Event2_Act2,
		C3.JavaScriptInEvents.Ads_Event2_Act3,
		C3.Plugins.System.Cnds.EveryTick,
		C3.JavaScriptInEvents.Ads_Event3_Act1,
		C3.JavaScriptInEvents.Ads_Event3_Act2,
		C3.JavaScriptInEvents.Ads_Event3_Act3,
		C3.JavaScriptInEvents.Ads_Event3_Act4,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.JavaScriptInEvents.Ads_Event10_Act1,
		C3.JavaScriptInEvents.Ads_Event11_Act1,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.Json.Exps.GetAsCompactString
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{Tween: 0},
	{Cookie: 0},
	{Fade: 0},
	{Bullet: 0},
	{Fall_Cookie: 0},
	{Face_cookie: 0},
	{Touch: 0},
	{Click_Icon: 0},
	{Radius: 0},
	{Orbit: 0},
	{Timer: 0},
	{Cursor: 0},
	{Keyboard: 0},
	{Cookie_txt: 0},
	{Sc: 0},
	{TouchActive: 0},
	{Item: 0},
	{Pn: 0},
	{Int_Price: 0},
	{r: 0},
	{nth: 0},
	{contribute: 0},
	{Item_btn: 0},
	{ItemPriceTxt: 0},
	{Qty: 0},
	{Qty_txt: 0},
	{Dictionary: 0},
	{ItemUnit_txt: 0},
	{Item_cookie_Icon: 0},
	{Sine2: 0},
	{Grandma: 0},
	{Name: 0},
	{Building_BG: 0},
	{Act: 0},
	{SellOrbuy_txt: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{BG: 0},
	{Title: 0},
	{Logo: 0},
	{play: 0},
	{Anchor: 0},
	{cc: 0},
	{cc_web: 0},
	{But_Sound: 0},
	{Btn_rate: 0},
	{Sprite: 0},
	{Restart_btn: 0},
	{Menu_btn: 0},
	{Rotate: 0},
	{Cookie2: 0},
	{Sprite3: 0},
	{CookieIcon: 0},
	{Farm: 0},
	{Factory: 0},
	{Mine: 0},
	{Bank: 0},
	{Shipment: 0},
	{Lab: 0},
	{Temple: 0},
	{WizardTower: 0},
	{TimeMachine: 0},
	{Portal: 0},
	{ChanceMaker: 0},
	{Prism: 0},
	{Condenser: 0},
	{Console: 0},
	{Engine: 0},
	{Idleverse: 0},
	{You: 0},
	{AJAX: 0},
	{ItemArray: 0},
	{Browser: 0},
	{ItemName_txt: 0},
	{CortexBaker: 0},
	{Sprite2: 0},
	{BarSlider: 0},
	{amount: 0},
	{Max: 0},
	{LayerNameScroll: 0},
	{DragDrop: 0},
	{Pin: 0},
	{slider: 0},
	{"9patch": 0},
	{Portalefx: 0},
	{flame: 0},
	{Sprite4: 0},
	{Active: 0},
	{Type: 0},
	{GUI: 0},
	{InputSon: 0},
	{InputSon2: 0},
	{Mouse: 0},
	{Asset815x: 0},
	{Asset115x: 0},
	{Asset315x: 0},
	{Asset215x: 0},
	{Asset615x: 0},
	{Asset515x: 0},
	{Asset415x: 0},
	{Asset715x: 0},
	{Nth: 0},
	{Increment: 0},
	{Price: 0},
	{UpgradesBtn: 0},
	{UpgradeIcon: 0},
	{Upgrades: 0},
	{OnScreenUpgrades: 0},
	{ItemsInfo: 0},
	{Iteminfo_title: 0},
	{Iteminfo_des: 0},
	{Iteminfo_price: 0},
	{CPC: 0},
	{CPS: 0},
	{dr: 0},
	{info2: 0},
	{x2Range: 0},
	{x2Glass: 0},
	{speed: 0},
	{ColorsValues: 0},
	{ColorNth: 0},
	{milk: 0},
	{Achievement_btn: 0},
	{AchievementTasks: 0},
	{Download_btn: 0},
	{Cryptography: 0},
	{BinaryData: 0},
	{Upload_btn: 0},
	{FileChooser: 0},
	{DataCount: 0},
	{DataSave: 0},
	{DataLoad: 0},
	{loadingtxt: 0},
	{msk: 0},
	{Building_BG_Frame: 0},
	{lvTxt: 0},
	{ItemGlobal: 0},
	{buttonPop: 0},
	{theme: 0},
	{btns: 0},
	{Cookies: 0},
	{Store_Cookie: 0},
	{SellOrbuy: 0},
	{Click: 0},
	{Click_Upgrade: 0},
	{UpgradeNth: 0},
	{TotalCPC: 0},
	{TotalCPS: 0},
	{AutoClick: 0},
	{"2x": 0},
	{Cookies_Achievement: 0},
	{CPS_Achievement: 0},
	{TotalAchievement: 0},
	{ObjectLimits: 0},
	{encryptPass: 0},
	{Sum: 0},
	{Row: 0},
	{x: 0},
	{y: 0},
	{Rotation: 0},
	{RandomPick: 0},
	{UpgradeCount: 0},
	{magnitude: 0},
	{Suffix: 0},
	{Number: 0},
	{value: 0},
	{CustomIndex: 0},
	{Sound: 0},
	{linktxt: 0},
	{Year: 0},
	{n: 0},
	{sntxt: 0},
	{Ads: 0},
	{adActive: 0},
	{adsInit: 0}
];

self.InstanceType = {
	Cookie: class extends self.ISpriteInstance {},
	Fall_Cookie: class extends self.ISpriteInstance {},
	Face_cookie: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Click_Icon: class extends self.ITextInstance {},
	Cursor: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Cookie_txt: class extends self.ITextInstance {},
	Item_btn: class extends self.ISpriteInstance {},
	ItemPriceTxt: class extends self.ITextInstance {},
	Qty_txt: class extends self.ITextInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	ItemUnit_txt: class extends self.ITextInstance {},
	Item_cookie_Icon: class extends self.ISpriteInstance {},
	Grandma: class extends self.ISpriteInstance {},
	Building_BG: class extends self.ISpriteInstance {},
	SellOrbuy_txt: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	BG: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	cc: class extends self.ITextInstance {},
	cc_web: class extends self.ITextInstance {},
	But_Sound: class extends self.ISpriteInstance {},
	Btn_rate: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Restart_btn: class extends self.ISpriteInstance {},
	Menu_btn: class extends self.ISpriteInstance {},
	Cookie2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	CookieIcon: class extends self.ISpriteInstance {},
	Farm: class extends self.ISpriteInstance {},
	Factory: class extends self.ISpriteInstance {},
	Mine: class extends self.ISpriteInstance {},
	Bank: class extends self.ISpriteInstance {},
	Shipment: class extends self.ISpriteInstance {},
	Lab: class extends self.ISpriteInstance {},
	Temple: class extends self.ISpriteInstance {},
	WizardTower: class extends self.ISpriteInstance {},
	TimeMachine: class extends self.ISpriteInstance {},
	Portal: class extends self.ISpriteInstance {},
	ChanceMaker: class extends self.ISpriteInstance {},
	Prism: class extends self.ISpriteInstance {},
	Condenser: class extends self.ISpriteInstance {},
	Console: class extends self.ISpriteInstance {},
	Engine: class extends self.ISpriteInstance {},
	Idleverse: class extends self.ISpriteInstance {},
	You: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	ItemArray: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	ItemName_txt: class extends self.ITextInstance {},
	CortexBaker: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	BarSlider: class extends self.ISpriteInstance {},
	slider: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	Portalefx: class extends self.ISpriteInstance {},
	flame: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	GUI: class extends self.ISpriteInstance {},
	InputSon: class extends self.ITiledBackgroundInstance {},
	InputSon2: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	Asset815x: class extends self.ISpriteInstance {},
	Asset115x: class extends self.ISpriteInstance {},
	Asset315x: class extends self.ISpriteInstance {},
	Asset215x: class extends self.ISpriteInstance {},
	Asset615x: class extends self.ISpriteInstance {},
	Asset515x: class extends self.ISpriteInstance {},
	Asset415x: class extends self.ISpriteInstance {},
	Asset715x: class extends self.ISpriteInstance {},
	UpgradesBtn: class extends self.ISpriteInstance {},
	UpgradeIcon: class extends self.ISpriteInstance {},
	Upgrades: class extends self.IArrayInstance {},
	OnScreenUpgrades: class extends self.IArrayInstance {},
	ItemsInfo: class extends self.IWorldInstance {},
	Iteminfo_title: class extends self.ITextInstance {},
	Iteminfo_des: class extends self.ITextInstance {},
	Iteminfo_price: class extends self.ITextInstance {},
	CPC: class extends self.ITextInstance {},
	CPS: class extends self.ITextInstance {},
	dr: class extends self.ITiledBackgroundInstance {},
	info2: class extends self.ITextInstance {},
	x2Range: class extends self.ITiledBackgroundInstance {},
	x2Glass: class extends self.ISpriteInstance {},
	milk: class extends self.ITiledBackgroundInstance {},
	Achievement_btn: class extends self.ISpriteInstance {},
	AchievementTasks: class extends self.ITextInstance {},
	Download_btn: class extends self.ISpriteInstance {},
	Cryptography: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	Upload_btn: class extends self.ISpriteInstance {},
	FileChooser: class extends self.IFileChooserInstance {},
	DataSave: class extends self.IJSONInstance {},
	DataLoad: class extends self.IJSONInstance {},
	loadingtxt: class extends self.ITextInstance {},
	msk: class extends self.ITiledBackgroundInstance {},
	Building_BG_Frame: class extends self.ISpriteInstance {},
	lvTxt: class extends self.ITextInstance {},
	ItemGlobal: class extends self.ISpriteInstance {},
	buttonPop: class extends self.ISpriteInstance {},
	theme: class extends self.ISpriteInstance {},
	btns: class extends self.ISpriteInstance {}
}